import { useEffect, useState } from 'react';
import { AlertCircle, BadgeDollarSign, CheckCircle2, LayoutDashboard, ReceiptText, TrendingUp, Users } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { api, money } from '../api/client';
import { Brand } from '../components/Brand';
import { useAuth } from '../auth/AuthContext';

type Metrics={activeSubscribers:number;complianceRate:number;rejectedPayments:number;monthlyRevenueCents:number;growthPercent:number;newSubscribers:number};
export function AdminDashboard(){const [m,setM]=useState<Metrics|null>(null);const [error,setError]=useState('');const {logout}=useAuth();const nav=useNavigate();useEffect(()=>{api<Metrics>('/admin/dashboard').then(setM).catch(e=>setError(e.message));},[]);return <div className="admin-shell"><aside className="admin-sidebar"><Brand admin/><nav><a className="active"><LayoutDashboard/>Dashboard</a><a><Users/>Assinaturas</a><a><ReceiptText/>Cobranças</a><a><Users/>Clientes</a></nav><button className="btn ghost full" onClick={()=>{logout();nav('/')}}>Sair</button></aside><main className="admin-main"><header className="admin-header"><div><h1>Dashboard do Clube</h1><p>Acompanhe assinaturas, cobranças e crescimento do XNaMai Club.</p></div><span className="admin-chip">Admin XNaMai</span></header>{error&&<div className="error-box">{error}</div>}{m&&<><section className="kpi-grid"><Kpi icon={<Users/>} title="Assinantes ativos" value={String(m.activeSubscribers)} note="Base ativa do clube"/><Kpi icon={<CheckCircle2/>} title="Adimplência" value={`${m.complianceRate}%`} note="Índice de pagamentos em dia" positive/><Kpi icon={<AlertCircle/>} title="Pagamentos recusados" value={String(m.rejectedPayments)} note="Aguardando recuperação" danger/><Kpi icon={<BadgeDollarSign/>} title="Receita mensal" value={money(m.monthlyRevenueCents)} note="Receita recebida no mês" positive/><Kpi icon={<TrendingUp/>} title="Crescimento" value={`${m.growthPercent>=0?'+':''}${m.growthPercent}%`} note="vs mês anterior" positive/></section><section className="admin-grid"><div className="panel chart-card"><div className="section-title"><h2>Receita mensal</h2><strong>{money(m.monthlyRevenueCents)}</strong></div><div className="fake-chart">{[45,58,66,73,82,96].map((x,i)=><div key={i} style={{height:`${x}%`}}><span></span></div>)}</div><div className="chart-months"><span>Mar</span><span>Abr</span><span>Mai</span><span>Jun</span><span>Jul</span><span>Ago</span></div></div><div className="panel admin-positive"><TrendingUp/><h2>Performance positiva</h2><strong>{m.newSubscribers} novos assinantes</strong><p>O clube mantém crescimento e alta adimplência.</p></div></section><section className="positive-strip"><div><CheckCircle2/><span><b>Receita em alta</b>{money(m.monthlyRevenueCents)} neste mês</span></div><div><TrendingUp/><span><b>Crescimento consistente</b>{m.growthPercent}% vs mês anterior</span></div><div><CheckCircle2/><span><b>Adimplência saudável</b>{m.complianceRate}% em dia</span></div></section></>}</main></div>}
function Kpi({icon,title,value,note,positive,danger}:{icon:React.ReactNode;title:string;value:string;note:string;positive?:boolean;danger?:boolean}){return <div className={`kpi ${positive?'positive':''} ${danger?'danger':''}`}><div className="kpi-icon">{icon}</div><div><span>{title}</span><strong>{value}</strong><small>{note}</small></div></div>}
